---
abstract: 'Portably create pipe() or pipe-like handles, one way or another.'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Pipely
requires:
  Errno: 1.09
  Fcntl: 0
  IO::Socket: 0
  Symbol: 0
  Test::More: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=IO-Pipely
  repository: git://github.com/rcaputo/io-pipely.git
version: 0.002
